### ISSUE TITLE
Icon Size Nothing Change

### ISSUE THREAD

**Issue by abdullah017** [vaetas/heroicons#11]
Icon size nothing changes.
The icon gets bigger when I want to enlarge it, but when I want to reduce the size by default, nothing changes.

**Comment by vaetas** [comment]
@abdullah017 can you please provide minimal working code of your problem? Thank you!

**Comment by abdullah017** [comment]
> @abdullah017 can you please provide minimal code example of your problem? Thank you!

HeroIcon(
      HeroIcons.calendar,
      solid: false, // Outlined icons are used by default.
      color: Colors.red,
      size: 30,
    );

**Comment by vaetas** [comment]
This is working for me. Can you share whole Widget you are using?

I'm not sure sure what you mean by "reduce size by default". You can change the size either by settings `size` property, or using `IconTheme`. See example project in this repo.

I see you are passing `HeroIcon` into `suffixIcon`. Without more info, I would guess that `suffixIcon` may change how `HeroIcon` looks.

**Comment by MassimoTambu** [comment]
Hi, I am having the same behaviour inside a TextField as a `prefixIcon`.
I tried either using an IconTheme with size or a size set in the HeroIcon class but none has worked.

<img width="1072" alt="Screenshot 2023-02-05 at 12 57 43" src="https://user-images.githubusercontent.com/57674329/216817327-43df4d9a-0f84-40bd-9f2f-99f62f8c2d1a.png">

Here's the code:
```dart
class StandsSearchTextBottomSheet extends StatelessWidget {
  const StandsSearchTextBottomSheet({super.key});

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      // * https://github.com/flutter/flutter/issues/39205#issuecomment-770953524
      minimum: EdgeInsets.only(
          top: MediaQueryData.fromWindow(WidgetsBinding.instance.window)
              .padding
              .top),
      child: Column(
        children: [
          SizedBox(
            height: 80,
            child: Padding(
              padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
              child: Row(
                children: [
                  IconButton(
                    onPressed: () => context.pop(),
                    icon: const HeroIcon(HeroIcons.arrowLeft),
                  ),
                  const SizedBox(width: 10),
                  Expanded(
                    child: TextField(
                      decoration: InputDecoration(
                        prefixIcon: const HeroIcon(
                          HeroIcons.magnifyingGlass,
                          // here's size property
                          size: 2,
                        ),
                        border: const OutlineInputBorder(),
                        hintText: 'Search'.hardcoded,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
          const Divider(),
          Expanded(
            child: ListView.builder(
                itemBuilder: (_, i) => Text(
                      '$i',
                      textAlign: TextAlign.center,
                    ),
                itemCount: 100),
          ),
        ],
      ),
    );
  }
}
```


I can see it doesn't work also with suffixIcon, but if I use the TextFields' properties `suffix`, `prefix` or `icon` works.
Is there maybe something that goes in conflict with the underneath configuration of `prefixIcon` and `suffixIcon`?

**Comment by SamJakob** [comment]
Encountered this myself and did some digging - it looks like if you use `BoxFit.scaleDown` in the `HeroIcon` class, it solves this issue for the search box, however issues then arise with `Icon` and `IconButton` (the icon is default size and does not scale).

Managed to solve the issue by wrapping the `SvgPicture` with a `FittedBox` (with `fit: BoxFit.scaleDown`) but leaving `fit: BoxFit.contain` on the SVG. I think this has the effect of forcing the SvgPicture into the desired size from the parent, but allows the SVG image itself to grow to meet that size.
