### ISSUE TITLE
 Svg Rendering is slow, please switch to ttf icons instead

### ISSUE THREAD

**Issue by prateekmedia** [vaetas/heroicons#2]
Additional information:
https://pub.dev/packages/icon_font_generator
https://pub.dev/packages/fantasticon_flutter

**Comment by vaetas** [comment]
Initially I tried to generate icon font using several generators (not these two) but some of the icons could not be converted correctly. Therefore I decided to use SVG rendering.

From my understanding, Hero Icons are meant to be used as SVG and maybe they use some weird features.

Could you check that the generators you mentioned generate correct output for all icons?

**Comment by vaetas** [comment]
I currently do not have any plans to using icon font instead. I would rather support customising icon properties like line thickness in app and this is only achievable by using SVG icons. Closing for now.
