### ISSUE TITLE
No named parameter with the name 'colorFilter'

### ISSUE THREAD

**Issue by Soeren86n** [vaetas/heroicons#20]
With Flutter version 3.19.6 I get the error message `Error (Xcode): ../../../.pub-cache/hosted/pub.dev/heroicons-0.10.0/lib/src/widget/heroicon.dart:138:9: Error: No named parameter with the name 'colorFilter'.` 
The colorFilter property is not supported in the SvgPicture.asset() function

**Comment by vaetas** [comment]
Please try this plugin with new Flutter versions or downgrade to older version of `heroicons`. I cannot reproduce this issue on the latest two versions of my Flutter.
